/**
 * Host web API + client module tests.
 *
 * Runs on a bare Node install with **no DSH host and no network**: the webServer
 * is a fake that records route registrations, the channel service is a fake, the
 * iLink login surface is injected through the plugin's public `deps` seam, and
 * the client half is evaluated against a stub `window.__ModuleLoader__` plus a
 * minimal React.
 *
 * The QR known-answer fixtures were generated by the independent MIT
 * `qrcode-generator` implementation (the canonical JavaScript encoder); the
 * encoder under test must reproduce them module for module, mask choice
 * included. Regenerating them needs that package and is deliberately not part of
 * this suite.
 *
 * @module wechat-feishu-linker/tests/web
 */

import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { mkdtemp, readFile, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import path from 'node:path'
import test, { beforeEach } from 'node:test'
import { fileURLToPath } from 'node:url'

import { createAccountStore } from '../src/ilink/store.js'
import { mountWebApi, resetWebApiMount } from '../src/web/index.js'
import { clearService, getService, setService } from '../src/registry.js'
import { WEB_API_PREFIX, createWebApi, reconnect } from '../src/web/routes.js'
import { byteCapacity, createQrMatrix, pickVersion, qrSvg } from '../src/web/qrcode.js'

// The web API is a process-level singleton — one route per prefix — so each test
// that mounts it must start from a clean slate.
beforeEach(() => resetWebApiMount())

const PACKAGE_ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)))
const CLIENT_PATH = path.join(PACKAGE_ROOT, 'client.js')

/**
 * Known-answer QR matrices, `rows` joined by `|`.
 *
 * Samples: the real WeChat lite-app link iLink returns for `bot_type=3`
 * (version 5), a short link (version 2), and a longer one that exercises the
 * version-information blocks plus two-block interleaving (version 7).
 */
const QR_FIXTURES = [

  // version 5, 37x37, 89 bytes
  '1111111010000111100010111101001111111|1000001010011100000100001000101000001|1011101011001011110101011010001011101|1011101011101101000000011010101011101|1011101001101001100000011111001011101|1000001011100100111100100000101000001|1111111010101010101010101010101111111|0000000000110011110001000011100000000|1100111000101011110101001000100101111|0101100110000101101010110011100010110|0011001001100101101001111001011101010|1110010101001011010111110010000101101|0001101101010110111101000101011100101|0001000110001011100011111101010011110|1011001101111111010011111001011110000|1001100100110100010101011011010101110|0000011000001101111101101001011000101|1000010111000110100010010101100011110|0000111110000001110001011011011010000|0100100110001011010001011010000110110|0010101101010110110101010011011100111|1010010101101001101010111101100111110|0101011111011111000011011001001001100|0101010101010100010011111010111000110|1001101010001101010111001010001000111|1111010011100111101001110001100010110|0010001001100001111001110111101000100|0010110011101010111111011010011000110|1110111100010110011101001001111111100|0000000010101001100010110100100011000|1111111000011111110000011000101011100|1000001011010100011111001011100010100|1011101011101100011111011000111110100|1011101000000111000000110101011001011|1011101001100001101010111101101100100|1000001010101011111001000000010100110|1111111010110110111101001001011110111',
  // version 2, 25x25, 30 bytes
  '1111111001111011001111111|1000001000111111101000001|1011101010000001001011101|1011101001000011101011101|1011101001110111001011101|1000001000111101001000001|1111111010101010101111111|0000000010001110100000000|1110111110011101111000100|1010110101001010011000001|0011011100100010100010111|1101010111100101000010010|1100101000101100011001011|0010100011101000101001001|1000111101001010111100111|0101100110001111010010010|1000011101111100111111000|0000000011100000100011011|1111111011000101101011011|1000001011110100100011011|1011101011000110111111010|1011101001001000000111100|1011101010000100100010001|1000001010010101100011010|1111111010100101111100011',
  // version 7, 45x45, 150 bytes
  '111111101110101000010100010000110100101111111|100000100101101101011100000001110101001000001|101110101101000011010111010000011001001011101|101110101000010111101110110001110001101011101|101110101100000101111111111100011111101011101|100000100011010110011000111010110000001000001|111111101010101010101010101010101010101111111|000000000010011000011000101010100011000000000|111100101110100001011111100111100110110011101|110111011110101000000100010001111001110100111|110101101001101101000100000000110110000100011|111000000110100011000111010000011011010001010|110011100110110111110110110001110000010000010|000001010011000101101001111100011100011101000|101011100111010110011111011010110001011010000|010111000111110101110001100110101110110011110|101110111000111010011011011100011001111100101|010100001100011110110010100110001111000110001|110001111110000000101001101100000111001111110|110100001010111000011100001011000000001010001|011111111010000001001111100111000110111110100|000110001001001000001000110001110001100010101|100010101101001101001010100001101010101010111|010110001100000011011000110001111000100010000|010011111101110111101111110001010001111111000|000001000111000101110011011100000101011101010|110010110011010110011010111101101000100111000|011111000100110101100001100110101101001101100|100111101001111010001100011100011101001011100|100111000101011110101000000111000111100110111|010010100001100000101100001100000111110100010|111010010101011000001100001110000110110111011|011011101000010001010111000010110000110000110|100100011111000000011110110100110100110000101|000010101011101101000001100010101011011100011|011110001011100011010111010000011011011011011|100110111000010111101111110001110000111110010|000000001010000101101000111100011101100010100|111111100011001110001010111010110000101011100|100000100000101101111000100011111010100010110|101110100010010010001111111100111011111111101|101110101110010110100111000100000110110000000|101110101101100000100110101011000011100001101|100000101001011000000001101011000000011110001|111111101110100001000111000111000110001100100',
]

const QR_SAMPLES = [

  'https://liteapp.weixin.qq.com/q/7GiQu1?qrcode=e1c41e09e49731f6e0361c42f00be170&bot_type=3',
  'https://liteapp.weixin.qq.com/',
  'https://liteapp.weixin.qq.com/q/v7?x=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
]

// ────────────────────────────── harness ──────────────────────────────

/** Let every pending promise chain settle. */
const settle = async () => {
  await new Promise((resolve) => setImmediate(resolve))
  await new Promise((resolve) => setImmediate(resolve))
}

/**
 * A minimal `ServerResponse` stand-in.
 *
 * @returns {object} response double.
 */
function createRes() {
  return {
    statusCode: 200,
    headers: {},
    body: '',
    headersSent: false,
    setHeader(name, value) {
      this.headers[String(name).toLowerCase()] = value
    },
    end(chunk) {
      this.body += chunk === undefined ? '' : String(chunk)
      this.headersSent = true
    },
    destroy() {},
  }
}

/**
 * A minimal `IncomingMessage` stand-in that emits its body asynchronously.
 *
 * @param {object} [init] - request shape.
 * @returns {object} request double.
 */
function createReq(init = {}) {
  const handlers = { data: [], end: [], error: [] }
  const req = {
    method: init.method ?? 'GET',
    url: init.url ?? '/',
    headers: { host: '127.0.0.1:19387', ...(init.headers ?? {}) },
    on(event, handler) {
      ;(handlers[event] ??= []).push(handler)
      return req
    },
    destroy() {},
  }
  queueMicrotask(() => {
    if (init.body !== undefined) {
      const chunk = Buffer.from(init.body)
      for (const handler of handlers.data) handler(chunk)
    }
    for (const handler of handlers.end) handler()
  })
  return req
}

/**
 * Call the API and parse the response.
 *
 * @param {object} api - `createWebApi` handle.
 * @param {object} [init] - request shape.
 * @returns {Promise<{status: number, headers: object, body: object, raw: string}>}
 * the response.
 */
async function call(api, init = {}) {
  const res = createRes()
  await api.handler(createReq(init), res)
  let body = null
  try {
    body = JSON.parse(res.body)
  } catch {
    body = null
  }
  return { status: res.statusCode, headers: res.headers, body, raw: res.body }
}

/**
 * An in-memory account store matching `createAccountStore`'s shape.
 *
 * @param {object | null} [initial] - starting account.
 * @returns {object} store double with its `state` exposed.
 */
function createMemoryStore(initial = null) {
  const state = { account: initial, saves: [], clears: 0, failSave: false }
  return {
    state,
    load: async () => state.account,
    save: async (account) => {
      if (state.failSave) throw new Error('disk full')
      state.account = account
      state.saves.push(account)
    },
    clear: async () => {
      state.account = null
      state.clears += 1
    },
    readBuf: async () => '',
    writeBuf: async () => {},
    path: 'memory://account.json',
  }
}

/**
 * Build the API under test with fake login endpoints and a fake store.
 *
 * @param {object} [options] - overrides.
 * @returns {{api: object, store: object, calls: object[]}} the handle.
 */
function createApi(options = {}) {
  const store = options.store ?? createMemoryStore()
  const calls = []
  const api = createWebApi({
    config: options.config ?? { baseUrl: 'https://ilinkai.test', dataDir: 'memory://' },
    // Channel-aware: the Feishu routes must get the Feishu service, not whatever
    // the WeChat slot happens to hold.
    getService: (channel) => (channel === 'feishu' ? options.feishuService : options.service),
    getBridgeSettings: options.getBridgeSettings,
    log: () => {},
    deps: {
      now: options.now,
      intervalMs: options.intervalMs,
      storeFactory: () => store,
      beginLogin: async (input) => {
        calls.push({ kind: 'beginLogin', input })
        if (options.beginError) throw options.beginError
        return options.beginResult ?? {
          qrcode: 'qr-1',
          qrUrl: 'https://liteapp.weixin.qq.com/q/abc?qrcode=qr-1&bot_type=3',
          expiresAt: Date.now() + 120000,
          expiresIn: 120,
        }
      },
      pollLogin: async (input) => {
        calls.push({ kind: 'pollLogin', input })
        if (options.pollError) throw options.pollError
        if (typeof options.pollResult === 'function') return options.pollResult(input)
        return options.pollResult ?? { status: 'pending' }
      },
    },
  })
  return { api, store, calls }
}

// ──────────────────────────── Cordis mounting ────────────────────────────

test('mountWebApi registers one prefix route, one error listener, and disposes them', () => {
  const routes = []
  const listeners = []
  const effects = []
  const webServer = {
    register(route) {
      routes.push(route)
      return () => {
        const at = routes.indexOf(route)
        if (at !== -1) routes.splice(at, 1)
      }
    },
  }
  const ctx = {
    get: (name) => (name === 'webServer' ? webServer : undefined),
    inject(names, callback) {
      assert.deepEqual(names, ['webServer'])
      callback(ctx)
    },
    on(event, handler) {
      listeners.push([event, handler])
      return () => {}
    },
    effect(fn) {
      effects.push(fn)
      return () => {}
    },
  }

  const dispose = mountWebApi(ctx, { log: () => {} })
  assert.equal(routes.length, 1)
  assert.equal(routes[0].kind, 'prefix')
  assert.equal(routes[0].path, WEB_API_PREFIX)
  assert.equal(typeof routes[0].handler, 'function')
  assert.equal(listeners.length, 1)
  assert.equal(listeners[0][0], 'wechat-ilink/error')
  assert.equal(effects.length, 1)

  dispose()
  assert.equal(routes.length, 0)
})

test('[REGRESSION] the mounted API answers a channel route with that channel service', async () => {
  // The WeChat service mounts this API and hands over itself. A lookup that
  // ignores the channel argument then answers the Feishu routes with the WeChat
  // service — and because both channels happen to have `beginLogin`, it answers
  // with a *plausible* payload (a WeChat QR) instead of an error. The card got a
  // QR url with no device code in it, which is a broken image and nothing else.
  const routes = []
  const webServer = {
    register(route) {
      routes.push(route)
      return () => {}
    },
  }
  const ctx = {
    get: (name) => (name === 'webServer' ? webServer : undefined),
    inject: (_names, callback) => callback(ctx),
    on: () => () => {},
    effect: () => () => {},
  }
  const wechat = {
    channel: 'wechat-ilink',
    getStatus: () => ({ channel: 'wechat-ilink', botId: 'wechat-bot' }),
    beginLogin: async () => ({ qrcode: 'wechat-qr', qrUrl: 'https://liteapp.weixin.qq.com/q/x', expiresAt: Date.now() }),
  }
  const feishu = {
    channel: 'feishu',
    getStatus: () => ({ channel: 'feishu', appId: 'cli_1', connected: false }),
    beginLogin: async () => ({ deviceCode: 'dc-1', qrUrl: 'https://open.feishu.cn/page/launcher', interval: 5000 }),
  }
  setService(wechat)
  setService(feishu)
  const dispose = mountWebApi(ctx, { log: () => {}, service: wechat })

  try {
    const res = createRes()
    await routes[0].handler(
      createReq({ url: `${WEB_API_PREFIX}/feishu/login/begin`, method: 'POST', body: '{}' }),
      res,
    )
    const body = JSON.parse(res.body)
    assert.equal(body.qrcode, 'dc-1', 'the Feishu route must reach the Feishu service')
    assert.match(body.qrImageUrl, /qrcode=dc-1$/)
    assert.ok(!String(body.qrUrl).includes('weixin.qq.com'), 'a WeChat QR is the wrong answer here')

    // And the WeChat routes still get the WeChat service.
    const own = createRes()
    await routes[0].handler(createReq({ url: `${WEB_API_PREFIX}/feishu/status` }), own)
    assert.equal(JSON.parse(own.body).status.channel, 'feishu')
  } finally {
    dispose()
    clearService()
  }
})

test('[REGRESSION] the Feishu row publishes itself and mounts the API on its own', async () => {
  // Two separate failures made the card report "the channel is not loaded" for a
  // perfectly healthy row: the Feishu service never published into the keyed
  // registry, and the web API was mounted only by the WeChat row — so a profile
  // that disables WeChat took the Feishu card's routes with it.
  const { apply: applyFeishu } = await import('wechat-feishu-linker/feishu')
  const routes = []
  const webServer = {
    register(route) {
      routes.push(route)
      return () => {}
    },
  }
  const ctx = {
    get: (name) => (name === 'webServer' ? webServer : undefined),
    inject: (_names, callback) => callback(ctx),
    on: () => () => {},
    effect: () => () => {},
    logger: undefined,
  }
  // No credentials on disk, so `start()` stays unbound and opens no socket.
  const channel = applyFeishu(ctx, { dataDir: 'memory://feishu-none' })
  try {
    assert.equal(getService('feishu'), channel, 'the row must publish itself')
    assert.equal(routes.length, 1, 'and mount the shared API when nobody else has')
    assert.equal(routes[0].path, WEB_API_PREFIX)

    const res = createRes()
    await routes[0].handler(createReq({ url: `${WEB_API_PREFIX}/feishu/status` }), res)
    const body = JSON.parse(res.body)
    assert.equal(body.mounted, true, 'the card must see a mounted row, not a missing one')
    assert.equal(body.status.channel, 'feishu')
  } finally {
    channel.dispose?.()
    clearService()
  }
})

test('mountWebApi degrades when the host has no webServer', () => {  const injected = []
  const ctx = {
    get: () => undefined,
    inject(names, callback) {
      injected.push(names)
      callback(ctx)
    },
  }
  assert.doesNotThrow(() => mountWebApi(ctx, { log: () => {} }))
  assert.deepEqual(injected, [['webServer']])
})

test('mountWebApi falls back to a direct webServer lookup without ctx.inject', () => {
  const routes = []
  const ctx = {
    get: (name) => (name === 'webServer' ? { register: (route) => (routes.push(route), () => {}) } : undefined),
  }
  mountWebApi(ctx, { log: () => {} })
  assert.equal(routes.length, 1)
  assert.equal(routes[0].path, WEB_API_PREFIX)
})

test('mountWebApi mirrors channel poll errors into lastError', async () => {
  let handler
  let listener
  const ctx = {
    get: () => undefined,
    inject: (_names, callback) =>
      callback({
        get: () => ({
          register: (route) => {
            handler = route.handler
            return () => {}
          },
        }),
      }),
    on: (_event, fn) => {
      listener = fn
      return () => {}
    },
  }
  mountWebApi(ctx, { log: () => {} })
  assert.equal(typeof handler, 'function')
  listener({ message: 'poll exploded' })

  const res = createRes()
  await handler(createReq({ url: `${WEB_API_PREFIX}/status` }), res)
  assert.equal(JSON.parse(res.body).lastError, 'poll exploded')
})

// ─────────────────────────────── /status ───────────────────────────────

test('GET /status reports a bound account without leaking the token', async () => {
  const service = {
    config: { baseUrl: 'https://ilinkai.test' },
    dataDirectory: 'memory://',
    token: 'super-secret-token',
    account: { botId: 'bot-42', accountId: 'bot-42' },
    connected: true,
    getStatus() {
      return { accountId: 'bot-42', connected: true, hasToken: true, dataDirectory: 'memory://' }
    },
  }
  const { api } = createApi({ service })
  const res = await call(api, { url: `${WEB_API_PREFIX}/status` })
  assert.equal(res.status, 200)
  assert.deepEqual(res.body, {
    bound: true,
    botId: 'bot-42',
    accountId: 'bot-42',
    connected: true,
    polling: true,
    lastError: null,
    // No bridge row is mounted in this fixture, so there is nothing to change
    // and nothing to report about the host surfaces it would have probed.
    settings: null,
    hostCompat: null,
    undelivered: null,
    catalog: null,
    permissions: null,
  })
  assert.ok(!res.raw.includes('super-secret-token'), 'bot_token must never reach the client')
})

test('GET /status falls back to the stored account when the service has not loaded it', async () => {
  const store = createMemoryStore({ accountId: 'stored-bot', botToken: 'stored-token', botId: 'stored-bot' })
  const service = {
    dataDirectory: 'memory://',
    connected: false,
    getStatus: () => ({ accountId: 'default', connected: false, hasToken: false }),
  }
  const { api } = createApi({ service, store })
  const res = await call(api, { url: `${WEB_API_PREFIX}/status` })
  assert.equal(res.body.bound, true)
  assert.equal(res.body.botId, 'stored-bot')
  assert.equal(res.body.accountId, 'stored-bot')
  assert.equal(res.body.polling, false)
  assert.ok(!res.raw.includes('stored-token'))
})

test('GET /status reports unbound with no service and no stored account', async () => {
  const { api } = createApi({ service: undefined })
  const res = await call(api, { url: `${WEB_API_PREFIX}/status` })
  assert.equal(res.status, 200)
  assert.deepEqual(res.body, {
    bound: false,
    botId: '',
    accountId: 'default',
    connected: false,
    polling: false,
    lastError: null,
    settings: null,
    hostCompat: null,
    undelivered: null,
    catalog: null,
    permissions: null,
  })
})

test('a throwing getStatus degrades instead of failing the request', async () => {
  const service = {
    dataDirectory: 'memory://',
    getStatus() {
      throw new Error('boom')
    },
  }
  const { api } = createApi({ service })
  const res = await call(api, { url: `${WEB_API_PREFIX}/status` })
  assert.equal(res.status, 200)
  assert.equal(res.body.bound, false)
})

// ──────────────────────────── /login/begin ────────────────────────────

test('POST /login/begin returns a QR, its rendered image URL, and the poll interval', async () => {
  const { api } = createApi({ service: undefined, intervalMs: 2500 })
  const res = await call(api, { method: 'POST', url: `${WEB_API_PREFIX}/login/begin` })
  assert.equal(res.status, 200)
  assert.equal(res.body.qrcode, 'qr-1')
  assert.match(res.body.qrUrl, /^https:\/\/liteapp\.weixin\.qq\.com\//)
  assert.equal(res.body.qrImageUrl, `${WEB_API_PREFIX}/qr.svg?qrcode=qr-1`)
  assert.equal(res.body.intervalMs, 2500)
  assert.ok(res.body.expiresAt > Date.now())

  const image = createRes()
  await api.handler(createReq({ url: `${WEB_API_PREFIX}/qr.svg?qrcode=qr-1` }), image)
  assert.equal(image.statusCode, 200)
  assert.match(image.headers['content-type'], /image\/svg\+xml/)
  assert.match(image.body, /^<svg /)
  assert.match(image.body, /#000000/)
})

test('POST /login/begin reports an upstream failure as 502 and records it', async () => {
  const { api } = createApi({ service: undefined, beginError: new Error('network down') })
  const res = await call(api, { method: 'POST', url: `${WEB_API_PREFIX}/login/begin` })
  assert.equal(res.status, 502)
  assert.equal(res.body.status, 'error')
  assert.match(res.body.message, /network down/)

  const status = await call(api, { url: `${WEB_API_PREFIX}/status` })
  assert.match(status.body.lastError, /network down/)
})

test('POST /login/begin rejects a payload without a QR code', async () => {
  const { api } = createApi({ service: undefined, beginResult: { qrcode: '', qrUrl: '' } })
  const res = await call(api, { method: 'POST', url: `${WEB_API_PREFIX}/login/begin` })
  assert.equal(res.status, 502)
  assert.equal(res.body.status, 'error')
})

test('GET /qr.svg answers 404 for an unknown qrcode', async () => {
  const { api } = createApi({ service: undefined })
  const res = await call(api, { url: `${WEB_API_PREFIX}/qr.svg?qrcode=nope` })
  assert.equal(res.status, 404)
})

// ───────────────────────────── /login/poll ─────────────────────────────

test('GET /login/poll requires the qrcode parameter', async () => {
  const { api } = createApi({ service: undefined })
  const res = await call(api, { url: `${WEB_API_PREFIX}/login/poll` })
  assert.equal(res.status, 400)
  assert.equal(res.body.status, 'error')
})

test('GET /login/poll rejects a qrcode this host never issued', async () => {
  const { api } = createApi({ service: undefined })
  const res = await call(api, { url: `${WEB_API_PREFIX}/login/poll?qrcode=ghost` })
  assert.equal(res.status, 200)
  assert.equal(res.body.status, 'error')
})

test('GET /login/poll passes pending and scanned through', async () => {
  const pending = createApi({ service: undefined, pollResult: { status: 'pending' } })
  await call(pending.api, { method: 'POST', url: `${WEB_API_PREFIX}/login/begin` })
  const pendingRes = await call(pending.api, { url: `${WEB_API_PREFIX}/login/poll?qrcode=qr-1` })
  assert.deepEqual(pendingRes.body, { status: 'pending' })

  const scanned = createApi({ service: undefined, pollResult: { status: 'scanned' } })
  await call(scanned.api, { method: 'POST', url: `${WEB_API_PREFIX}/login/begin` })
  const scannedRes = await call(scanned.api, { url: `${WEB_API_PREFIX}/login/poll?qrcode=qr-1` })
  assert.deepEqual(scannedRes.body, { status: 'scanned' })
})

test('GET /login/poll writes credentials on success and never returns the token', async () => {
  const store = createMemoryStore()
  const reloaded = []
  const service = {
    dataDirectory: 'memory://',
    reload: async () => reloaded.push('reload'),
  }
  const { api } = createApi({
    service,
    store,
    pollResult: { status: 'success', botToken: 'fresh-token', botId: 'bot-9' },
  })
  await call(api, { method: 'POST', url: `${WEB_API_PREFIX}/login/begin` })
  const res = await call(api, { url: `${WEB_API_PREFIX}/login/poll?qrcode=qr-1` })

  assert.equal(res.status, 200)
  assert.deepEqual(res.body, { status: 'success', botId: 'bot-9' })
  assert.ok(!res.raw.includes('fresh-token'))
  assert.equal(store.state.account.botToken, 'fresh-token')
  assert.equal(store.state.account.botId, 'bot-9')
  assert.equal(store.state.account.accountId, 'bot-9')
  assert.deepEqual(reloaded, ['reload'])

  // The QR is consumed: a second poll reports an error rather than succeeding twice.
  const again = await call(api, { url: `${WEB_API_PREFIX}/login/poll?qrcode=qr-1` })
  assert.equal(again.body.status, 'error')
})

test('GET /login/poll reports a credential write failure instead of claiming success', async () => {
  const store = createMemoryStore()
  store.state.failSave = true
  const { api } = createApi({
    service: undefined,
    store,
    pollResult: { status: 'success', botToken: 'fresh-token', botId: 'bot-9' },
  })
  await call(api, { method: 'POST', url: `${WEB_API_PREFIX}/login/begin` })
  const res = await call(api, { url: `${WEB_API_PREFIX}/login/poll?qrcode=qr-1` })
  assert.equal(res.body.status, 'error')
  assert.match(res.body.message, /凭据写入失败/)
})

test('GET /login/poll reports a success payload without a token as an error', async () => {
  const { api } = createApi({ service: undefined, pollResult: { status: 'success' } })
  await call(api, { method: 'POST', url: `${WEB_API_PREFIX}/login/begin` })
  const res = await call(api, { url: `${WEB_API_PREFIX}/login/poll?qrcode=qr-1` })
  assert.equal(res.body.status, 'error')
  assert.match(res.body.message, /未取到凭据/)
})

test('[REGRESSION] a service success with nothing on disk is not a bind', async () => {
  // The other half of the same coin: the service answers `success` and the
  // response rightly carries no token, but nothing was actually stored.
  // Reporting success here is the state the contact only discovers on the next
  // restart — which is exactly what 「登录成功但未取到凭据」 describes.
  const service = {
    dataDirectory: 'memory://',
    beginLogin: async () => ({
      qrcode: 'svc-qr2',
      qrUrl: 'https://liteapp.weixin.qq.com/q/svc2',
      expiresAt: Date.now() + 60000,
    }),
    pollLogin: async () => ({ available: true, ok: true, status: 'success', botId: 'bot-9' }),
  }
  const { api } = createApi({ service, store: createMemoryStore() })
  await call(api, { method: 'POST', url: `${WEB_API_PREFIX}/login/begin` })
  const res = await call(api, { url: `${WEB_API_PREFIX}/login/poll?qrcode=svc-qr2` })

  assert.equal(res.status, 200)
  assert.equal(res.body.status, 'error')
  assert.match(res.body.message, /未取到凭据/)
})

test('GET /login/poll marks the QR expired and forgets it', async () => {
  const { api } = createApi({ service: undefined, pollResult: { status: 'expired' } })
  await call(api, { method: 'POST', url: `${WEB_API_PREFIX}/login/begin` })
  const res = await call(api, { url: `${WEB_API_PREFIX}/login/poll?qrcode=qr-1` })
  assert.deepEqual(res.body, { status: 'expired' })
  const again = await call(api, { url: `${WEB_API_PREFIX}/login/poll?qrcode=qr-1` })
  assert.equal(again.body.status, 'error')
})

test('GET /login/poll expires a QR locally without calling iLink again', async () => {
  let now = 1_000_000
  const { api, calls } = createApi({
    service: undefined,
    now: () => now,
    beginResult: { qrcode: 'qr-1', qrUrl: 'https://liteapp.weixin.qq.com/q/x', expiresAt: now + 1000 },
  })
  await call(api, { method: 'POST', url: `${WEB_API_PREFIX}/login/begin` })
  now += 5000
  const res = await call(api, { url: `${WEB_API_PREFIX}/login/poll?qrcode=qr-1` })
  assert.deepEqual(res.body, { status: 'expired' })
  assert.equal(calls.filter((entry) => entry.kind === 'pollLogin').length, 0)
})

test('GET /login/poll turns a transport failure into status error', async () => {
  const { api } = createApi({ service: undefined, pollError: new Error('socket closed') })
  await call(api, { method: 'POST', url: `${WEB_API_PREFIX}/login/begin` })
  const res = await call(api, { url: `${WEB_API_PREFIX}/login/poll?qrcode=qr-1` })
  assert.equal(res.status, 200)
  assert.equal(res.body.status, 'error')
  assert.match(res.body.message, /socket closed/)
})

test('GET /login/poll prefers the channel service methods when present', async () => {
  const seen = []
  const service = {
    dataDirectory: 'memory://',
    beginLogin: async () => ({
      qrcode: 'svc-qr',
      qrUrl: 'https://liteapp.weixin.qq.com/q/svc',
      expiresAt: Date.now() + 60000,
    }),
    pollLogin: async (qrcode) => {
      seen.push(qrcode)
      return { status: 'pending' }
    },
  }
  const { api, calls } = createApi({ service })
  const begin = await call(api, { method: 'POST', url: `${WEB_API_PREFIX}/login/begin` })
  assert.equal(begin.body.qrcode, 'svc-qr')
  const poll = await call(api, { url: `${WEB_API_PREFIX}/login/poll?qrcode=svc-qr` })
  assert.equal(poll.body.status, 'pending')
  assert.deepEqual(seen, ['svc-qr'])
  assert.equal(calls.length, 0, 'the protocol layer must not be touched when the service owns the flow')
})

test('[REGRESSION] the channel service owns login: a tokenless success IS a success', async () => {
  // The service stores the credential and reconnects *before* it returns, and
  // its result carries no token by design — the HTTP surface must never echo
  // one. Requiring a token from this path made a real, successful WeChat bind
  // answer 「登录成功但未取到凭据，请重新扫码」 while the credentials were already
  // on disk and the channel was already polling. Only the protocol fallback
  // (the two tests above) sees a token, so only that branch may demand one.
  const seen = []
  const service = {
    dataDirectory: 'memory://',
    beginLogin: async () => ({
      qrcode: 'svc-qr',
      qrUrl: 'https://liteapp.weixin.qq.com/q/svc',
      expiresAt: Date.now() + 60000,
    }),
    pollLogin: async (qrcode) => {
      seen.push(qrcode)
      return { available: true, ok: true, status: 'success', botId: 'bot-9' }
    },
  }
  const { api, calls } = createApi({
    service,
    // The real service persists the credential before it answers; the fixture has
    // to model that, or it describes a service that claims a bind it never made.
    store: createMemoryStore({ accountId: 'bot-9', botToken: 'tok-9', botId: 'bot-9' }),
  })
  await call(api, { method: 'POST', url: `${WEB_API_PREFIX}/login/begin` })
  const res = await call(api, { url: `${WEB_API_PREFIX}/login/poll?qrcode=svc-qr` })

  assert.equal(res.status, 200)
  assert.deepEqual(res.body, { status: 'success', botId: 'bot-9' })
  assert.deepEqual(seen, ['svc-qr'])
  assert.equal(calls.length, 0, 'the protocol layer must not be touched when the service owns the flow')

  // The QR is consumed: a second poll reports an error rather than succeeding twice.
  const again = await call(api, { url: `${WEB_API_PREFIX}/login/poll?qrcode=svc-qr` })
  assert.equal(again.body.status, 'error')
})

test('GET /login/poll surfaces a channel service failure without consuming the QR', async () => {
  // `Service.pollLogin` reports a transport failure as `ok:false` with no
  // `status`, so the route must land on `error` and pass the message through.
  // The QR survives: a transient poll failure must not force a re-scan.
  const service = {
    dataDirectory: 'memory://',
    beginLogin: async () => ({
      qrcode: 'svc-qr',
      qrUrl: 'https://liteapp.weixin.qq.com/q/svc',
      expiresAt: Date.now() + 60000,
    }),
    pollLogin: async () => ({ available: true, ok: false, reason: 'login-poll-failed', message: 'socket closed' }),
  }
  const { api } = createApi({ service })
  await call(api, { method: 'POST', url: `${WEB_API_PREFIX}/login/begin` })
  const res = await call(api, { url: `${WEB_API_PREFIX}/login/poll?qrcode=svc-qr` })

  assert.equal(res.body.status, 'error')
  assert.match(res.body.message, /socket closed/)

  const retry = await call(api, { url: `${WEB_API_PREFIX}/login/poll?qrcode=svc-qr` })
  assert.equal(retry.body.status, 'error', 'the QR must still be registered for a retry')
  assert.doesNotMatch(retry.body.message, /未登记/)
})

test('credentials survive a real file-backed store round-trip', async () => {
  const dir = await mkdtemp(path.join(tmpdir(), 'wechat-feishu-linker-web-'))
  try {
    const api = createWebApi({
      config: { baseUrl: 'https://ilinkai.test', dataDir: dir },
      getService: () => undefined,
      log: () => {},
      deps: {
        storeFactory: (dataDir) => createAccountStore({ dataDir }),
        beginLogin: async () => ({
          qrcode: 'qr-disk',
          qrUrl: 'https://liteapp.weixin.qq.com/q/disk',
          expiresAt: Date.now() + 60000,
        }),
        pollLogin: async () => ({ status: 'success', botToken: 'disk-token', botId: 'disk-bot' }),
      },
    })
    await call(api, { method: 'POST', url: `${WEB_API_PREFIX}/login/begin` })
    const res = await call(api, { url: `${WEB_API_PREFIX}/login/poll?qrcode=qr-disk` })
    assert.deepEqual(res.body, { status: 'success', botId: 'disk-bot' })

    const stored = JSON.parse(await readFile(path.join(dir, 'account.json'), 'utf8'))
    assert.equal(stored.botToken, 'disk-token')
    assert.equal(stored.botId, 'disk-bot')

    const status = await call(api, { url: `${WEB_API_PREFIX}/status` })
    assert.equal(status.body.bound, true)
    assert.equal(status.body.botId, 'disk-bot')
    assert.ok(!status.raw.includes('disk-token'))

    const logout = await call(api, { method: 'POST', url: `${WEB_API_PREFIX}/logout` })
    assert.equal(logout.body.ok, true)
    const after = await call(api, { url: `${WEB_API_PREFIX}/status` })
    assert.equal(after.body.bound, false)
  } finally {
    await rm(dir, { recursive: true, force: true })
  }
})

// ─────────────────────────────── /logout ───────────────────────────────

test('POST /logout stops the channel, clears the store, and forgets the cached account', async () => {
  const store = createMemoryStore({ accountId: 'bot-1', botToken: 'token-1', botId: 'bot-1' })
  const service = {
    dataDirectory: 'memory://',
    account: { botId: 'bot-1', botToken: 'token-1' },
    client: { fake: true },
    connected: true,
    stopped: false,
    stopCalls: 0,
    async stop() {
      this.stopCalls += 1
      this.connected = false
    },
    getStatus() {
      return { accountId: 'bot-1', connected: this.connected, hasToken: Boolean(this.account) }
    },
  }
  const { api } = createApi({ service, store })
  const before = await call(api, { url: `${WEB_API_PREFIX}/status` })
  assert.equal(before.body.bound, true)

  const res = await call(api, { method: 'POST', url: `${WEB_API_PREFIX}/logout` })
  assert.equal(res.status, 200)
  assert.equal(res.body.ok, true)
  assert.equal(service.stopCalls, 1)
  assert.equal(store.state.clears, 1)
  assert.equal(service.account, undefined)
  assert.equal(service.client, undefined)

  const after = await call(api, { url: `${WEB_API_PREFIX}/status` })
  assert.equal(after.body.bound, false)
})

test('POST /logout prefers a service logout method', async () => {
  const store = createMemoryStore({ accountId: 'bot-1', botToken: 'token-1' })
  let called = 0
  const service = {
    dataDirectory: 'memory://',
    account: { botToken: 'token-1' },
    stop: async () => {},
    async logout() {
      called += 1
      this.account = undefined
    },
    getStatus: () => ({ accountId: 'default', connected: false, hasToken: false }),
  }
  const { api } = createApi({ service, store })
  const res = await call(api, { method: 'POST', url: `${WEB_API_PREFIX}/logout` })
  assert.equal(res.body.ok, true)
  assert.equal(called, 1)
})

test('POST /logout still clears the store without any service', async () => {
  const store = createMemoryStore({ accountId: 'bot-1', botToken: 'token-1' })
  const { api } = createApi({ service: undefined, store })
  const res = await call(api, { method: 'POST', url: `${WEB_API_PREFIX}/logout` })
  assert.equal(res.status, 200)
  assert.equal(res.body.ok, true)
  assert.equal(store.state.clears, 1)
})

// ─────────────────────── workspaces / sessions / bind ───────────────────────

test('GET /workspaces degrades when the host offers no workspace capability', async () => {
  const { api } = createApi({ service: {} })
  const res = await call(api, { url: `${WEB_API_PREFIX}/workspaces` })
  assert.equal(res.status, 200)
  assert.equal(res.body.available, false)
  assert.deepEqual(res.body.items, [])
  assert.match(res.body.message, /未提供工作区能力/)
})

test('GET /workspaces normalizes service rows and drops non-primitives', async () => {
  const service = {
    listWorkspaces: async () => [
      { id: 'ws-1', name: '项目', path: 'F:\\work', cwd: 'F:\\work', current: true, nested: { big: true } },
      { id: 'ws-2', name: 'other', path: 'G:\\other' },
      null,
      'not-a-row',
    ],
  }
  const { api } = createApi({ service })
  const res = await call(api, { url: `${WEB_API_PREFIX}/workspaces` })
  assert.equal(res.body.available, true)
  assert.deepEqual(res.body.items, [
    { id: 'ws-1', name: '项目', path: 'F:\\work', cwd: 'F:\\work', current: true },
    { id: 'ws-2', name: 'other', path: 'G:\\other' },
  ])
})

test('GET /workspaces accepts a wrapped { items } payload and reports failures', async () => {
  const wrapped = createApi({ service: { getWorkspaces: async () => ({ items: [{ id: 'a', name: 'A' }] }) } })
  const ok = await call(wrapped.api, { url: `${WEB_API_PREFIX}/workspaces` })
  assert.deepEqual(ok.body.items, [{ id: 'a', name: 'A' }])

  const broken = createApi({
    service: {
      listWorkspaces: async () => {
        throw new Error('registry offline')
      },
    },
  })
  const failed = await call(broken.api, { url: `${WEB_API_PREFIX}/workspaces` })
  assert.equal(failed.status, 500)
  assert.equal(failed.body.available, false)
  assert.match(failed.body.message, /registry offline/)
})

test('GET /sessions forwards the workspace filter and degrades without the capability', async () => {
  const seen = []
  const service = {
    listSessions: async (input) => {
      seen.push(input)
      return { items: [{ sessionId: 'session-1', title: '对话', cwd: 'F:\\work', updatedAt: '2026-01-01', extra: 1 }] }
    },
  }
  const { api } = createApi({ service })
  const filtered = await call(api, { url: `${WEB_API_PREFIX}/sessions?workspace=${encodeURIComponent('F:\\work')}` })
  assert.deepEqual(seen, [{ workspace: 'F:\\work' }])
  assert.deepEqual(filtered.body.items, [
    { sessionId: 'session-1', title: '对话', cwd: 'F:\\work', updatedAt: '2026-01-01' },
  ])

  const plain = await call(api, { url: `${WEB_API_PREFIX}/sessions` })
  assert.deepEqual(seen[1], undefined)
  assert.equal(plain.body.available, true)

  const missing = await call(createApi({ service: {} }).api, { url: `${WEB_API_PREFIX}/sessions` })
  assert.equal(missing.body.available, false)
  assert.match(missing.body.message, /未提供会话列表能力/)
})

test('POST /bind validates its body', async () => {
  const { api } = createApi({ service: {} })
  const empty = await call(api, { method: 'POST', url: `${WEB_API_PREFIX}/bind`, body: '{}' })
  assert.equal(empty.status, 400)
  assert.match(empty.body.message, /至少提供/)

  const malformed = await call(api, { method: 'POST', url: `${WEB_API_PREFIX}/bind`, body: '{oops' })
  assert.equal(malformed.status, 400)
  assert.match(malformed.body.message, /合法 JSON/)

  const huge = await call(api, {
    method: 'POST',
    url: `${WEB_API_PREFIX}/bind`,
    body: JSON.stringify({ workspace: 'x'.repeat(70 * 1024) }),
  })
  assert.equal(huge.status, 413)
})

test('POST /bind degrades when the capability is missing and forwards when present', async () => {
  const missing = await call(createApi({ service: {} }).api, {
    method: 'POST',
    url: `${WEB_API_PREFIX}/bind`,
    body: JSON.stringify({ workspace: 'F:\\work' }),
  })
  assert.equal(missing.status, 200)
  assert.equal(missing.body.ok, false)
  assert.equal(missing.body.available, false)

  const seen = []
  const service = {
    bind: async (input) => {
      seen.push(input)
      return { ok: true, workspace: input.workspace, sessionId: 'session-7' }
    },
  }
  const bound = await call(createApi({ service }).api, {
    method: 'POST',
    url: `${WEB_API_PREFIX}/bind`,
    body: JSON.stringify({ workspace: 'F:\\work', sessionId: 'session-7' }),
  })
  assert.deepEqual(seen, [{ workspace: 'F:\\work', sessionId: 'session-7' }])
  assert.deepEqual(bound.body, { ok: true, available: true, workspace: 'F:\\work', sessionId: 'session-7' })

  const refused = await call(
    createApi({ service: { setBinding: async () => ({ ok: false, message: '会话不存在' }) } }).api,
    { method: 'POST', url: `${WEB_API_PREFIX}/bind`, body: JSON.stringify({ sessionId: 'ghost' }) },
  )
  assert.equal(refused.body.ok, false)
  assert.match(refused.body.message, /会话不存在/)
})

// ──────────────────────────── routing / fencing ────────────────────────────

test('unknown endpoints and wrong methods are rejected', async () => {
  const { api } = createApi({ service: {} })
  const missing = await call(api, { url: `${WEB_API_PREFIX}/nope` })
  assert.equal(missing.status, 404)

  const wrongMethod = await call(api, { method: 'POST', url: `${WEB_API_PREFIX}/status` })
  assert.equal(wrongMethod.status, 405)
  assert.equal(wrongMethod.headers.allow, 'GET')

  const wrongMethod2 = await call(api, { method: 'GET', url: `${WEB_API_PREFIX}/logout` })
  assert.equal(wrongMethod2.status, 405)
})

test('a cross-site browser request is refused', async () => {
  const { api } = createApi({ service: {} })
  const crossSite = await call(api, {
    url: `${WEB_API_PREFIX}/status`,
    headers: { 'sec-fetch-site': 'cross-site' },
  })
  assert.equal(crossSite.status, 403)

  const foreignOrigin = await call(api, {
    url: `${WEB_API_PREFIX}/status`,
    headers: { origin: 'https://evil.example' },
  })
  assert.equal(foreignOrigin.status, 403)

  const sameOrigin = await call(api, {
    url: `${WEB_API_PREFIX}/status`,
    headers: { origin: 'http://127.0.0.1:19387' },
  })
  assert.equal(sameOrigin.status, 200)
})

test('dispose stops serving', async () => {
  const { api } = createApi({ service: {} })
  api.dispose()
  const res = await call(api, { url: `${WEB_API_PREFIX}/status` })
  assert.equal(res.status, 503)
})

// ─────────────────────────────── reconnect ───────────────────────────────

test('reconnect prefers service methods, then the documented shim, and never throws', async () => {
  assert.equal(await reconnect(undefined, {}), 'no-service')
  assert.equal(await reconnect({ reload: async () => {} }, {}), 'reload')
  assert.equal(await reconnect({ reload: async () => { throw new Error('nope') } }, {}), 'reload-failed')

  const channel = {
    started: true,
    stopped: false,
    calls: [],
    async stop() {
      this.calls.push('stop')
      this.stopped = true
    },
    async start() {
      this.calls.push('start')
      this.started = true
    },
  }
  assert.equal(await reconnect(channel, {}), 'restart-shim')
  assert.deepEqual(channel.calls, ['stop', 'start'])
  assert.equal(channel.started, true)
  assert.equal(channel.stopped, false)

  const idle = {
    started: false,
    stopped: false,
    calls: [],
    async stop() {
      this.calls.push('stop')
    },
    async start() {
      this.calls.push('start')
    },
  }
  assert.equal(await reconnect(idle, {}), 'restart-shim-skipped')
  assert.deepEqual(idle.calls, ['stop'])
})

// ─────────────────────────────── QR encoder ───────────────────────────────

test('the QR encoder reproduces the reference matrices module for module', () => {
  assert.equal(QR_FIXTURES.length, QR_SAMPLES.length)
  for (let index = 0; index < QR_SAMPLES.length; index += 1) {
    const { modules } = createQrMatrix(QR_SAMPLES[index])
    const rows = modules.map((row) => row.map((dark) => (dark ? '1' : '0')).join(''))
    assert.deepEqual(rows, QR_FIXTURES[index].split('|'), `sample ${index}`)
  }
})

test('QR version selection and capacity boundaries', () => {
  assert.equal(byteCapacity(1), 17)
  assert.equal(byteCapacity(5), 106)
  assert.equal(byteCapacity(10), 271)
  assert.equal(pickVersion(17), 1)
  assert.equal(pickVersion(18), 2)
  assert.equal(pickVersion(106), 5)
  assert.equal(pickVersion(107), 6)
  assert.equal(pickVersion(271), 10)
  assert.throws(() => pickVersion(272), RangeError)
  assert.throws(() => createQrMatrix(''), TypeError)
  assert.throws(() => createQrMatrix('x'.repeat(300)), RangeError)
})

test('qrSvg renders a standalone scannable image', () => {
  const svg = qrSvg('https://example.com/q/abc')
  assert.match(svg, /^<svg xmlns="http:\/\/www\.w3\.org\/2000\/svg"/)
  assert.match(svg, /fill="#ffffff"/)
  assert.match(svg, /fill="#000000"/)
  assert.match(svg, /shape-rendering="crispEdges"/)
  assert.match(svg, /data-qr-version="2"/)
  assert.ok(!svg.includes('--dsw-alias-'), 'a QR image must not inherit theme tokens')
})

// ─────────────────────────────── client half ───────────────────────────────

/**
 * Minimal React with just the hooks the section uses, enough to render and
 * re-render against a stable hook store.
 *
 * @returns {{api: object, effects: object[], runEffects: () => Promise<void>, reset: () => void}}
 * the double.
 */
function createFakeReact() {
  const hooks = []
  const effects = []
  const cleanups = []
  let cursor = 0
  return {
    effects,
    reset() {
      cursor = 0
    },
    async runEffects() {
      const pending = effects.splice(0, effects.length)
      for (const entry of pending) {
        const result = entry.fn()
        if (result && typeof result.then === 'function') await result
        else if (typeof result === 'function') cleanups.push(result)
      }
      await settle()
    },
    /** Run every captured effect cleanup so no timer keeps the test process alive. */
    cleanupAll() {
      for (const fn of cleanups.splice(0, cleanups.length)) fn()
    },
    api: {
      createElement(type, props, ...children) {
        return { type, props: { ...(props ?? {}), children: children.length <= 1 ? children[0] : children } }
      },
      useState(initial) {
        const index = cursor++
        if (!(index in hooks)) hooks[index] = typeof initial === 'function' ? initial() : initial
        return [
          hooks[index],
          (next) => {
            hooks[index] = typeof next === 'function' ? next(hooks[index]) : next
          },
        ]
      },
      useEffect(fn) {
        effects.push({ fn })
        cursor += 1
      },
      useCallback(fn) {
        cursor += 1
        return fn
      },
      useMemo(fn) {
        cursor += 1
        return fn()
      },
      useRef(initial) {
        const index = cursor++
        if (!(index in hooks)) hooks[index] = { current: initial }
        return hooks[index]
      },
    },
  }
}

/**
 * Load the client module against a stub `window` and a stub `fetch`.
 *
 * @param {Function} [fetchImpl] - replacement fetch.
 * @returns {{source: string, spec: object, react: object}} the captured spec.
 */
function loadClient(fetchImpl) {
  const source = readFileSync(CLIENT_PATH, 'utf8')
  const react = createFakeReact()
  let spec
  const windowStub = {
    __ModuleLoader__: {
      load(candidate) {
        spec = candidate
      },
    },
  }
  const factory = new Function('window', 'fetch', 'setTimeout', 'clearTimeout', source)
  factory(
    windowStub,
    fetchImpl ?? (async () => {
      throw new Error('the client must not fetch during load/apply')
    }),
    setTimeout,
    clearTimeout,
  )
  assert.ok(spec, 'the client module must register itself with __ModuleLoader__')
  return { source, spec, react }
}

/**
 * Register the client module into the settings slot and return its component.
 *
 * @param {object} spec - client module spec from {@link loadClient}.
 * @param {object} react - fake React.
 * @returns {{component: Function, options: object, injected: string[]}} the registration.
 */
function mountSection(spec, react) {
  const registrations = []
  const injected = []
  spec.factory(() => react.api).apply({
    slots: {
      inject(key, callback) {
        injected.push(key)
        return callback()
      },
      register(options, component) {
        registrations.push({ options, component })
        return () => {}
      },
    },
  })
  assert.deepEqual(injected, ['settings.section'])
  assert.equal(registrations.length, 1)
  return { ...registrations[0], injected }
}

/**
 * Walk a rendered tree depth-first.
 *
 * @param {object} node - tree node.
 * @param {(node: object) => boolean} predicate - matcher.
 * @returns {object | undefined} the first match.
 */
function findNode(node, predicate) {
  if (node === null || typeof node !== 'object') return undefined
  if (Array.isArray(node)) {
    for (const child of node) {
      const found = findNode(child, predicate)
      if (found) return found
    }
    return undefined
  }
  if (predicate(node)) return node
  return findNode(node.props?.children, predicate)
}

/**
 * Collect every string child in a tree.
 *
 * @param {object} node - tree node.
 * @param {string[]} [into] - accumulator.
 * @returns {string[]} the strings.
 */
function collectStrings(node, into = []) {
  if (node === null || typeof node !== 'object') return into
  if (Array.isArray(node)) {
    for (const child of node) collectStrings(child, into)
    return into
  }
  if (typeof node.props?.children === 'string') into.push(node.props.children)
  collectStrings(node.props?.children, into)
  return into
}

/**
 * Remove block and line comments from JavaScript source.
 *
 * @param {string} source - source text.
 * @returns {string} the source with comments blanked out.
 */
function stripComments(source) {
  return source
    .replace(/\/\*[\s\S]*?\*\//g, ' ')
    .replace(/(^|[^:])\/\/[^\n]*/g, '$1')
}

test('client.js loads lazily, requires only react, and registers the settings section', () => {
  const { source, spec, react } = loadClient()
  assert.equal(spec.id, 'wechat-feishu-linker')
  assert.equal(typeof spec.factory, 'function')

  // No Harness client package may be imported, and no DOM may be touched outside
  // the component subtree. Comments are stripped first so the header prose that
  // *documents* those rules cannot trip the check.
  const code = stripComments(source)
  assert.ok(!/require\(\s*['"]@deepseek-ai/.test(code), 'no @deepseek-ai require')
  assert.ok(!/from\s+['"]@deepseek-ai/.test(code), 'no @deepseek-ai import')
  assert.ok(!/\bdocument\b/.test(code), 'the client must not touch document directly')

  const mod = spec.factory((name) => {
    assert.equal(name, 'react')
    return react.api
  })
  assert.deepEqual(mod.inject, ['slots'])
  assert.equal(typeof mod.apply, 'function')

  const registration = mountSection(spec, react)
  assert.equal(registration.options.name, 'settings.section')
  assert.equal(registration.options.id, 'wechat-ilink')
  assert.equal(typeof registration.options.order, 'number')
  // The section now covers both channels, so its label names the bot rather
  // than WeChat alone — the two channel cards inside say which is which.
  assert.equal(registration.options.label, 'ClawBot 设置')
})

test('the settings section renders a theme-token-only, self-contained tree', () => {
  const { spec, react } = loadClient()
  const { component } = mountSection(spec, react)

  react.reset()
  const tree = component({ close: () => {} })

  assert.equal(tree.type, 'div')
  assert.equal(tree.props.className, 'wil_root')

  const style = findNode(tree, (node) => node.type === 'style')
  assert.ok(style, 'the section renders its own stylesheet inside its subtree')
  const css = style.props.children
  assert.match(css, /--dsw-alias-/)
  assert.ok(!/#[0-9a-fA-F]{3,8}\b/.test(css), 'no literal hex colours in the stylesheet')
  assert.ok(!/\brgba?\(/.test(css), 'no literal rgb()/rgba() colours')
  assert.ok(!/\bhsla?\(/.test(css), 'no literal hsl() colours')

  const labels = collectStrings(tree)
  assert.ok(labels.includes('微信'), 'the WeChat card names its channel')
  assert.ok(labels.includes('飞书'), 'and so does the Feishu card')
  assert.ok(labels.includes('加载中'), 'the initial state is visible before any fetch resolves')
  assert.ok(labels.includes('扫码绑定'), 'the bind affordance is reachable')
  assert.ok(labels.some((label) => label.includes('正在加载')), 'the workspace panel degrades while loading')
})

test('the settings section reports a host without a Web service', async () => {
  const { spec, react } = loadClient()
  const { component } = mountSection(spec, react)

  react.reset()
  component({})
  await react.runEffects()

  react.reset()
  const tree = component({})
  const labels = collectStrings(tree)
  assert.ok(
    labels.some((label) => label.includes('当前宿主未启用 Web 服务')),
    `expected the degraded host message, got: ${labels.join(' | ')}`,
  )
})

test('the settings section binds, shows the QR, and polls to success', async () => {
  const requests = []
  let bound = false
  const fetchImpl = async (url, init) => {
    requests.push({ url, method: init?.method ?? 'GET' })
    if (url.endsWith('/login/begin')) {
      return {
        ok: true,
        status: 200,
        json: async () => ({
          qrcode: 'qr-live',
          qrUrl: 'https://liteapp.weixin.qq.com/q/live',
          qrImageUrl: '/wechat-ilink/api/qr.svg?qrcode=qr-live',
          expiresAt: Date.now() + 60000,
          intervalMs: 5,
        }),
      }
    }
    if (url.includes('/login/poll')) {
      bound = true
      return { ok: true, status: 200, json: async () => ({ status: 'success', botId: 'bot-live' }) }
    }
    if (url.endsWith('/status')) {
      return {
        ok: true,
        status: 200,
        json: async () => ({
          bound,
          botId: bound ? 'bot-live' : '',
          accountId: bound ? 'bot-live' : 'default',
          connected: bound,
          polling: bound,
          lastError: null,
        }),
      }
    }
    return { ok: true, status: 200, json: async () => ({ available: false, items: [] }) }
  }

  const { spec, react } = loadClient(fetchImpl)
  const { component } = mountSection(spec, react)

  try {
    react.reset()
    component({})
    await react.runEffects()
    react.reset()
    let tree = component({})

    const bindButton = findNode(tree, (node) => node.type === 'button' && collectStrings(node).includes('扫码绑定'))
    assert.ok(bindButton, 'the bind button is rendered for an unbound channel')

    bindButton.props.onClick()
    await settle()
    react.reset()
    tree = component({})

    const image = findNode(tree, (node) => node.type === 'img')
    assert.ok(image, 'the QR image appears after /login/begin')
    assert.equal(image.props.src, '/wechat-ilink/api/qr.svg?qrcode=qr-live')
    assert.ok(requests.some((entry) => entry.url.endsWith('/login/begin') && entry.method === 'POST'))

    // Arm the poll loop, then let its timer fire: the mocked endpoint answers
    // `success` on the first poll.
    await react.runEffects()
    await new Promise((resolve) => setTimeout(resolve, 40))
    react.reset()
    tree = component({})
    const labels = collectStrings(tree)
    assert.ok(labels.includes('绑定成功'), `expected the success phase, got: ${labels.join(' | ')}`)
    assert.ok(requests.some((entry) => entry.url.includes('/login/poll?qrcode=qr-live')))
  } finally {
    react.cleanupAll()
  }
})

// ─────────────────────────── runtime settings routes ───────────────────────────

/**
 * A bridge settings handle double that keeps one value, like the real one.
 *
 * @param {object} [initial] - starting settings.
 * @returns {object} `{ read, write, writes }`.
 */
function createSettingsHandle(initial = { displayMode: 'compact', typingIndicator: true }) {
  let current = { ...initial }
  const writes = []
  return {
    writes,
    read: () => ({ ...current }),
    write: async (patch) => {
      writes.push(patch)
      if (patch.displayMode !== undefined && patch.displayMode !== 'compact' && patch.displayMode !== 'quiet') {
        return { ok: false, message: 'displayMode 只能是 compact 或 quiet' }
      }
      current = { ...current, ...patch }
      return { ok: true, settings: { ...current }, persisted: true }
    },
  }
}

test('GET /status carries the live settings so the page can render them', async () => {
  const handle = createSettingsHandle({ displayMode: 'quiet', typingIndicator: false })
  const { api } = createApi({ getBridgeSettings: () => handle })
  const res = await call(api, { url: `${WEB_API_PREFIX}/status` })
  assert.equal(res.status, 200)
  assert.deepEqual(res.body.settings, { displayMode: 'quiet', typingIndicator: false })
})

test('POST /settings writes through the bridge and answers with what it now holds', async () => {
  const handle = createSettingsHandle()
  const { api } = createApi({ getBridgeSettings: () => handle })
  const res = await call(api, {
    url: `${WEB_API_PREFIX}/settings`,
    method: 'POST',
    body: JSON.stringify({ displayMode: 'quiet' }),
  })
  assert.equal(res.status, 200)
  assert.deepEqual(res.body, {
    ok: true,
    settings: { displayMode: 'quiet', typingIndicator: true },
    persisted: true,
  })
  assert.deepEqual(handle.writes, [{ displayMode: 'quiet' }])
})

test('POST /settings rejects a value the bridge does not implement', async () => {
  const handle = createSettingsHandle()
  const { api } = createApi({ getBridgeSettings: () => handle })
  const res = await call(api, {
    url: `${WEB_API_PREFIX}/settings`,
    method: 'POST',
    body: JSON.stringify({ displayMode: 'full' }),
  })
  assert.equal(res.status, 400)
  assert.equal(res.body.ok, false)
  assert.match(res.body.message, /displayMode/)
})

test('POST /settings says so when the bridge row is not running', async () => {
  // `settings: null` in `/status` and this response are how the page knows to
  // explain itself instead of offering a control that cannot do anything.
  const { api } = createApi({ getBridgeSettings: () => undefined })
  const res = await call(api, {
    url: `${WEB_API_PREFIX}/settings`,
    method: 'POST',
    body: JSON.stringify({ displayMode: 'quiet' }),
  })
  assert.equal(res.status, 200)
  assert.equal(res.body.ok, false)
  assert.equal(res.body.available, false)
  assert.match(res.body.message, /桥接未运行/)
})

// ──────────────────────────── Feishu channel routes ────────────────────────────

/**
 * A Feishu service double, shaped like `FeishuChannel`.
 *
 * @param {object} [over] - overrides.
 * @returns {object} the double.
 */
function createFeishuService(over = {}) {
  return {
    getStatus: () => ({
      channel: 'feishu',
      bound: false,
      appId: '',
      connected: false,
      connectionState: 'unbound',
      ...(over.status ?? {}),
    }),
    beginLogin:
      over.beginLogin ??
      (async () => ({
        deviceCode: 'dc-1',
        qrUrl: 'https://open.feishu.cn/page/launcher?user_code=ABCD-1234&from=sdk',
        userCode: 'ABCD-1234',
        interval: 5000,
        expiresAt: Date.now() + 600_000,
      })),
    pollLogin: over.pollLogin ?? (async () => ({ status: 'pending', interval: 5000 })),
    bind: over.bind ?? (async () => ({ ok: true })),
    logout: over.logout ?? (async () => {}),
  }
}

test('GET /feishu/status distinguishes a missing row from an unbound one', async () => {
  // "The plugin row is not loaded" and "no credentials yet" look identical from
  // the outside, and only one of them is fixed by typing something.
  const missing = createApi({ feishuService: undefined })
  const absent = await call(missing.api, { url: `${WEB_API_PREFIX}/feishu/status` })
  assert.equal(absent.status, 200)
  assert.equal(absent.body.mounted, false)

  const present = createApi({ feishuService: createFeishuService() })
  const there = await call(present.api, { url: `${WEB_API_PREFIX}/feishu/status` })
  assert.equal(there.body.mounted, true)
  assert.equal(there.body.status.connectionState, 'unbound')
})

test('[REGRESSION] the QR the registration returns is actually servable as an image', async () => {
  // The card renders this URL straight into an <img>. A URL the image route does
  // not recognise is a broken image in the UI and nothing else — no error, no
  // log, just a QR that never appears.
  const { api } = createApi({ feishuService: createFeishuService() })

  const begun = await call(api, { url: `${WEB_API_PREFIX}/feishu/login/begin`, method: 'POST', body: '{}' })
  assert.equal(begun.status, 200)
  assert.equal(begun.body.ok, true)
  assert.equal(begun.body.qrcode, 'dc-1')
  assert.match(begun.body.qrImageUrl, /\/feishu\/qr\.svg\?qrcode=dc-1$/)

  const imagePath = begun.body.qrImageUrl.slice(begun.body.qrImageUrl.indexOf(WEB_API_PREFIX))
  const image = await call(api, { url: imagePath })
  assert.equal(image.status, 200, `the image route must serve ${imagePath}`)
  assert.match(image.headers['content-type'], /image\/svg\+xml/)
  assert.match(image.raw, /^<svg/u)
  assert.ok(image.raw.length > 500, 'a real QR, not an empty frame')
})

test('the image route refuses a code this process never issued', async () => {
  // The URL is read from the server's own record, so a request can never have an
  // arbitrary URL rendered as a QR and handed back to the browser.
  const { api } = createApi({ feishuService: createFeishuService() })
  const res = await call(api, { url: `${WEB_API_PREFIX}/feishu/qr.svg?qrcode=not-mine` })
  assert.equal(res.status, 404)
})

test('POST /feishu/login/poll passes the outcome through', async () => {
  const { api } = createApi({
    feishuService: createFeishuService({
      pollLogin: async () => ({ status: 'success', appId: 'cli_0123456789abcdef', bound: true }),
    }),
  })
  await call(api, { url: `${WEB_API_PREFIX}/feishu/login/begin`, method: 'POST', body: '{}' })
  const res = await call(api, { url: `${WEB_API_PREFIX}/feishu/login/poll?qrcode=dc-1` })
  assert.equal(res.status, 200)
  assert.equal(res.body.status, 'success')
  assert.equal(res.body.appId, 'cli_0123456789abcdef')
})

test('POST /feishu/login/poll needs a code and a live channel', async () => {
  const { api } = createApi({ feishuService: createFeishuService() })
  const noCode = await call(api, { url: `${WEB_API_PREFIX}/feishu/login/poll` })
  assert.equal(noCode.status, 400)

  const noChannel = createApi({ feishuService: undefined })
  const missing = await call(noChannel.api, { url: `${WEB_API_PREFIX}/feishu/login/poll?qrcode=dc-1` })
  assert.equal(missing.status, 400)
})

test('a refused scan begin reports the platform message instead of a QR', async () => {
  const { api } = createApi({
    feishuService: createFeishuService({
      beginLogin: async () => {
        throw new Error('当前飞书环境不支持一键创建应用')
      },
    }),
  })
  const res = await call(api, { url: `${WEB_API_PREFIX}/feishu/login/begin`, method: 'POST', body: '{}' })
  assert.equal(res.status, 502)
  assert.match(res.body.message, /不支持一键创建应用/)
})

test('POST /feishu/bind says the row is missing rather than failing silently', async () => {
  const { api } = createApi({ feishuService: undefined })
  const res = await call(api, {
    url: `${WEB_API_PREFIX}/feishu/bind`,
    method: 'POST',
    body: JSON.stringify({ appId: 'cli_0123456789abcdef', appSecret: 's' }),
  })
  assert.equal(res.status, 200)
  assert.equal(res.body.available, false)
  assert.match(res.body.message, /飞书通道未运行/)
})

test('GET /settings is not a route', async () => {
  const { api } = createApi({ getBridgeSettings: () => createSettingsHandle() })
  const res = await call(api, { url: `${WEB_API_PREFIX}/settings` })
  assert.equal(res.status, 405)
})
